# Generated by Django 3.2.9 on 2021-11-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0003_auto_20211122_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
